Repository Open-Sn/opensn, pull requests merged in 2024-06, with the labels that each got.

#292 No more local Vec3
  framework/mesh/logical_volume/rcc_logical_volume.cc
  framework/mesh/mesh_continuum/mesh_continuum.h
  framework/mesh/mesh_generator/extruder_mesh_generator.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_aggregation/angle_aggregation.cc
  test/framework/tutorials/tutorial_06_wdd.cc
  test/framework/tutorials/tutorial_91a_pwld.cc
  test/framework/tutorials/tutorial_93_raytracing.cc
Labels: maintenance

#288 fixing transfer and production matrices when reading them for openmc
  framework/materials/multi_group_xs/openmc_import.cc
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_U235.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_UO2.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
Labels: bug-fix

#293 update to install instructions. also change to highest md header for u…
  doc/install_linux.md
  doc/install_linux_easy.md
  doc/install_macos.md
  doc/install_macos_easy.md
Labels: documentation

#299 Minor change to PETSc initialization to suppress warnings about unused command line options
  lua/framework/lua_app.cc
Labels: maintenance

#295 Adding developer workflow instructions
  doc/index.rst
  doc/workflow.md
Labels: documentation

#301 Updating processing order of cli options
  lua/framework/lua_app.cc
Labels: bug-fix

#294 Theory manual and some doco clean up
  README.md
  doc/CMakeLists.txt
  doc/coding_standard.md
  doc/conf.py.in
  doc/getting_started.rst
  doc/index.rst
  doc/references.bib
  doc/requirements.txt
  doc/start_developer_tutorials.md
  doc/start_install.md
  doc/start_source_code_doc.md
  doc/start_user_tutorials.md
  doc/theory/adjoint.rst
  doc/theory/background.rst
  doc/theory/cross_sections.rst
  doc/theory/discretization.rst
  doc/theory/images/P12GLC.png
  doc/theory/images/P8GLC.png
  doc/theory/images/PWL_degen_pentagon1.png
  doc/theory/images/PWL_degen_pentagon2.png
  doc/theory/images/PWL_pentagon.png
  doc/theory/images/ProcGraph.png
  doc/theory/images/ProcMesh.png
  doc/theory/images/SLDFESQBasen2.png
  doc/theory/images/SLDFESQr.png
  doc/theory/images/T8GLC.png
  doc/theory/images/ThreeDTetrahedral.png
  doc/theory/images/algo1.png
  doc/theory/images/algo2.png
  doc/theory/images/algo3.png
  doc/theory/images/sweeps_example.png
  doc/theory/index.rst
  doc/theory/iterative.rst
  doc/theory/outcome.rst
  doc/theory/parallelization.rst
  tutorials/index.rst
  tutorials/old/basic_diffusion_simulation.md
  tutorials/old/basic_transport_simulation.md
  tutorials/old/index.rst
  tutorials/old/output.md
Labels: documentation

#306 Fixing a long-standing bug with Richardson iteration
  framework/math/linear_solver/linear_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/lbs_iterative_methods.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  test/framework/tutorials/tutorial_93_raytracing.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_jfnk.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_scdsa.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_smm.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock_cbc.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_4_dsa_ortho_inf.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
Labels: bug-fix

#308 Adding stylua check into gha QA workflow
  .github/workflows/qa.yaml
  tutorials/MeshingExamples/MatIDsBndryIDFromLua.lua
  tutorials/lbs/first/first_example.lua
  tutorials/material/mg_xs.lua
  tutorials/meshing/extrusion.lua
  tutorials/meshing/ortho_2D.lua
  tutorials/meshing/ortho_3D.lua
  tutorials/meshing/read_2D_msh.lua
  tutorials/meshing/read_2D_obj.lua
  tutorials/meshing/read_3D_vtu.lua
Labels: task

#290 Fixing balance calculation with reflecting boundary conditions
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
  test/modules/linear_boltzmann_solvers/transport_steady/1g_infinite_pure_absorber_balance_gmres.lua
  test/modules/linear_boltzmann_solvers/transport_steady/1g_infinite_pure_absorber_balance_richardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/HDPE.h5
  test/modules/linear_boltzmann_solvers/transport_steady/hdpe_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/HDPE.h5
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/hdpe_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/tests.json
Labels: bug-fix

#312 add input to regression suite and format update to 2 test files
  test/modules/linear_boltzmann_solvers/transport_steady/hdpe_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/simple_scatter.xs
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_4_dsa_ortho_inf.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/hdpe_balance.lua
Labels: regression test
