Repository Open-Sn/opensn, pull requests merged in 2024-05, with the labels that each got.

#219 Refactoring mesh reading capability
  framework/mesh/io/gmsh_io.cc
  framework/mesh/io/mesh_io.h
  framework/mesh/io/obj_io.cc
  framework/mesh/io/vtk_io.cc
  framework/mesh/mesh.cc
  framework/mesh/mesh.h
  framework/mesh/mesh_continuum/mesh_continuum.cc
  framework/mesh/mesh_continuum/mesh_continuum.h
  framework/mesh/mesh_generator/extruder_mesh_generator.cc
  framework/mesh/mesh_generator/extruder_mesh_generator.h
  framework/mesh/mesh_generator/from_file_mesh_generator.cc
  framework/mesh/mesh_generator/from_file_mesh_generator.h
  framework/mesh/mesh_generator/mesh_generator.cc
  framework/mesh/mesh_generator/mesh_generator.h
  framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
  framework/mesh/mesh_generator/orthogonal_mesh_generator.h
  framework/mesh/mesh_generator/split_file_mesh_generator.cc
  framework/mesh/mesh_generator/split_file_mesh_generator.h
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
  lua/framework/mesh/unpartitioned_mesh/create.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
  test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
  test/framework/tutorials/tutorial_06_wdd.cc
  test/framework/tutorials/tutorial_91a_pwld.cc
  test/framework/tutorials/tutorial_93_raytracing.cc
Labels: maintenance

#241 Removing dead and duplicate code
  framework/mesh/mesh.cc
  framework/mesh/mesh.h
Labels: maintenance

#232 Initial commit of tools directory
  tools/README.md
  tools/developer/lsan.supp
  tools/xs/create_openmc_xslib.ipynb
Labels: enhancement

#247 Refactoring HDF utilities to use the HDF C interface instead of the C++ interface
  CMakeLists.txt
  framework/materials/multi_group_xs/openmc_import.cc
  framework/utils/hdf_utils.h
  resources/configure_dependencies.py
Labels: maintenance

#248 Do not serialize non-POD types
  framework/mesh/cell/cell.cc
  test/framework/data_types/data_types_test_00.cc
Labels: bug-fix

#253 Removing PETSc forward declarations
  framework/field_functions/field_function_grid_based.h
  framework/math/parallel_vector/parallel_vector.h
  framework/math/petsc_utils/petsc_forward_declarations.h
  test/framework/math/math_test_02.cc
Labels: maintenance

#254 Removing custom typedef in `sldfe_sq.cc`
  framework/math/quadratures/angular/sldfe_sq_quadrature.cc
Labels: maintenance

#258 IsotropicMultiGrpSource -> IsotropicMultiGroupSource
  framework/materials/isotropic_multigroup_source.h
  framework/materials/scalar_value.h
  lua/framework/materials/lua_material.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
  modules/mg_diffusion/mg_diffusion_solver.h
Labels: small fix/improvement, maintenance

#250 adding reed problem with balance checks
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  test/modules/linear_boltzmann_solvers/transport_steady/reed_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
Labels: regression test

#264 Generate JSON compile commands database
  CMakeLists.txt
Labels: maintenance

#262 Refactoring `JoinWords` macros
  framework/object_factory.h
  framework/post_processors/post_processor_printer.cc
  framework/utils/utils.h
  lua/framework/console/console.h
Labels: maintenance

#265 Removing unused field-function operations
  framework/field_functions/operations/field_copy.cc
  framework/field_functions/operations/field_copy.h
  framework/field_functions/operations/field_operation.cc
  framework/field_functions/operations/field_operation.h
  framework/field_functions/operations/multi_field.cc
  framework/field_functions/operations/multi_field.h
  framework/field_functions/operations/partitioner_predicate.cc
  framework/field_functions/operations/partitioner_predicate.h
  lua/framework/physics/field_operations/field_ops_lua.cc
Labels: maintenance

#261 Updating field function interpolations
  external/mpicpp-lite/impl/Communicator.h
  framework/field_functions/interpolation/ffinter_line.cc
  framework/field_functions/interpolation/ffinter_line.h
  framework/field_functions/interpolation/ffinter_point.cc
  framework/field_functions/interpolation/ffinter_point.h
  framework/field_functions/interpolation/ffinter_slice.cc
  framework/field_functions/interpolation/ffinter_slice.h
  framework/field_functions/interpolation/ffinter_volume.cc
  framework/field_functions/interpolation/ffinter_volume.h
  framework/field_functions/interpolation/ffinterpolation.h
  framework/mesh/mesh_continuum/mesh_continuum.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_export.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_get_value.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_lua.h
  lua/framework/mesh/field_function_interpolation/ffinterpol_set_property.cc
  test/modules/cfem_diffusion/c_diffusion_2d_1a_linear.lua
  test/modules/dfem_diffusion/d_diffusion_2d_1a_linear.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_5_poly_a_ani_hetero_bndry.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1a_extruder.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
Labels: small fix/improvement, maintenance, bug-fix

#266 Materials Lua Interface Refactor
  framework/math/math_vector_nx.h
  framework/mesh/mesh_vector.h
  lua/framework/materials/lua_material.cc
  lua/framework/materials/lua_material.h
  test/modules/linear_boltzmann_solvers/transport_steady/reed_balance.lua
Labels: enhancement

#268 Fixing field function export calls for lines and slices
  test/modules/cfem_diffusion/c_diffusion_2d_1a_linear.lua
  test/modules/dfem_diffusion/d_diffusion_2d_1a_linear.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_5_poly_a_ani_hetero_bndry.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1a_extruder.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
Labels: bug-fix

#269 Minor refactor of power iteration classes
  modules/linear_boltzmann_solvers/executors/lbs_steady_state.cc
  modules/linear_boltzmann_solvers/executors/nl_keigen.cc
  modules/linear_boltzmann_solvers/executors/nl_keigen.h
  modules/linear_boltzmann_solvers/executors/pi_keigen.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.h
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.h
  test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_1d_1g.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1a_qblock.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1b_qblock.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_1d_1g.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_1d_1g_cbc.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock_cbc.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock_cbc.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock_cbc.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_cset.lua
Labels: maintenance

#271 Fixing a minor memory issue in the discrete ordinates solver destructor
  framework/runtime.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.h
Labels: bug-fix

#277 Groupset solver doesn't honor GMRES restart parameter
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/tests.json
Labels: bug-fix

#278 Throw an exception if the user forgets to call MeshGenerator.Execute()
  framework/mesh/mesh.cc
Labels: bug-fix

#279 Fixing weekly tests to run only one day a week and not for PRs
  .github/workflows/weekly.yaml
Labels: maintenance

#270 Updating `CFEMSolver` to use InputParameters construction
  lua/modules/cfem_diffusion/lua_cfem_diff_solver.cc
  lua/modules/cfem_diffusion/lua_cfem_diff_solver.h
  lua/modules/modules_lua.cc
  modules/cfem_diffusion/cfem_diffusion_bndry.h
  modules/cfem_diffusion/cfem_diffusion_solver.cc
  modules/cfem_diffusion/cfem_diffusion_solver.h
  test/modules/cfem_diffusion/c_diffusion_2d_1a_linear.lua
  test/modules/cfem_diffusion/c_diffusion_2d_2a_dir_bcs.lua
  test/modules/cfem_diffusion/c_diffusion_2d_2b_robin_bcs.lua
  test/modules/cfem_diffusion/c_diffusion_2d_3a_analytical_coef.lua
  test/modules/cfem_diffusion/c_diffusion_2d_3b_analytical_coef2.lua
Labels: maintenance

#282 GitHub Linguist tuning
  .gitattributes
Labels: maintenance
