Repository Open-Sn/opensn, pull requests merged in 2024-10, with the labels that each got.

#373 Fixing compile problems with gcc-11
  modules/linear_boltzmann_solvers/lbs_solver/io/lbs_solver_io.h
Labels: maintenance

#371 Correctly size `offsets` in `FieldFunctionInterpolationLine::ExportToCSV`
  framework/field_functions/interpolation/ffinter_line.cc
Labels: bug-fix

#369 Use correct API call for exporting field functions
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
Labels: bug-fix

#366 Updating installation instructions
  doc/install_linux_easy.md
  doc/install_macos_easy.md
Labels: documentation, bug-fix

#375 Precursors accessor bug fix
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Labels: bug-fix

#379 Updating sanitizer build.
  .github/workflows/builds.yaml
Labels: maintenance

#359 Refactoring NDArray for performance
  framework/data_types/ndarray.h
Labels: maintenance

#382 Removing GLL quadrature option.
  framework/math/quadratures/angular/product_quadrature.cc
  framework/math/quadratures/angular/product_quadrature.h
  lua/framework/math/quadratures/create_curvilinear_product_quadrature.cc
  lua/framework/math/quadratures/create_prod_quadrature.cc
  lua/framework/math/quadratures/quadratures.h
Labels: maintenance

#380 Adding support for Gmsh v4.1 ASCII format. Minor refactoring of Gmsh v2.2 ASCII reader.
  framework/mesh/io/gmsh_io.cc
  framework/mesh/io/gmsh_io_v22.cc
  framework/mesh/io/gmsh_io_v41.cc
  framework/mesh/io/mesh_io.h
  test/assets/mesh/InclusionsGmshV2.msh
  test/assets/mesh/InclusionsGmshV4.msh
  test/assets/mesh/Rectangular2D2MatGmsh.geo
  test/assets/mesh/Rectangular2D2MatGmshV2.msh
  test/assets/mesh/Rectangular2D2MatGmshV4.msh
  test/modules/linear_boltzmann_solvers/transport_steady/diag_XS_64g_1mom_c0.99.xs
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v4.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v4.lua
Labels: enhancement

#383 Adding missing #include
  framework/data_types/ndarray.h
Labels: maintenance

#376 Adding support for MPI-distributed meshes.
  framework/mesh/mesh_generator/distributed_mesh_generator.cc
  framework/mesh/mesh_generator/distributed_mesh_generator.h
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6a_dist_mesh.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6b_dist_mesh.lua
Labels: enhancement

#385 Fixing errors found by clang sanitizer
  framework/materials/multi_group_xs/multi_group_xs.cc
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.cc
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.h
  framework/math/unknown_manager/unknown_manager.cc
  framework/mesh/mesh_continuum/grid_face_histogram.cc
  framework/mesh/mesh_continuum/mesh_continuum.cc
  framework/mesh/mesh_generator/extruder_mesh_generator.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
  modules/point_reactor_kinetics/point_reactor_kinetics.cc
Labels: maintenance
