Repository Open-Sn/opensn, pull requests merged in 2024-07, with the labels that each got.

#317 Removing references to ChiTech
  .gitignore
  external/README.md
  framework/field_functions/field_function_grid_based.cc
  framework/math/spatial_discretization/cell_mappings/cell_mapping.cc
  framework/math/statistics/cdfsampler.cc
  framework/math/vector_ghost_communicator/vector_ghost_communicator.cc
  framework/physics/solver_base/solver.cc
  framework/utils/timer.h
  lua/framework/console/console.h
  lua/framework/logging/log.h
  lua/framework/mpi/mpi_barrier.h
  lua/modules/linear_bolzmann_solvers/do_transient/lbts_lua_advance_time_data.cc
  lua/modules/linear_bolzmann_solvers/do_transient/lbts_lua_create_solver.cc
  lua/modules/linear_bolzmann_solvers/do_transient/lbts_lua_get_property.cc
  lua/modules/linear_bolzmann_solvers/do_transient/lbts_lua_set_property.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/print_sweep_ordering.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/iterative_operations/lbts_set_sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/lbts_callback.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/lbts_step_precursors.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/lbts_transient_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/lbts_transient_solver.h
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/sweep_chunks/lbts_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_transient_solver/sweep_chunks/lbts_sweep_chunk_pwl.h
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_residual_func.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
  resources/configure_a_module.py
  test/framework/data_types/gold/data_types_test_00.lua.gold
  test/framework/graphs/gold/kba_graph_partitioner.lua.gold
  test/framework/math/gold/math_test_00.lua.gold
  test/framework/math/gold/math_test_01_wdd_ijk_sweep.lua.gold
  test/framework/math/gold/math_test_02.lua.gold
  test/framework/math/quadrature/gold/quadrature_test1.lua.gold
  test/framework/misc_utils/gold/misc_utils_test_00.lua.gold
  test/framework/parameters/gold/params_test_00.lua.gold
  test/framework/tutorials/simtest_92_dsa.temp
  test/framework/tutorials/simtest_92b_dsa_pwlc.temp
  test/framework/tutorials/xs_graphite_pure.xs
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/Reference.txt
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/Reference2.txt
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/xs_3_170.xs
Labels: maintenance

#316 Updating mpicpp-lite to version 1.2.0
  external/mpicpp-lite/impl/Communicator.h
Labels: maintenance

#319 adding chi to xs
  framework/materials/multi_group_xs/multi_group_xs.cc
  framework/materials/multi_group_xs/multi_group_xs.h
  framework/materials/multi_group_xs/openmc_import.cc
  framework/materials/multi_group_xs/opensn_import.cc
  lua/framework/materials/multi_group_xs/multi_group_xs_lua_utils.cc
  test/framework/materials/tests.json
  test/framework/materials/xs_lua_printout.lua
Labels: small fix/improvement

#318 Removing naked pointers in favor of `std::shared_ptr`
  framework/data_types/ndarray.h
  framework/math/statistics/cdfsampler.cc
  framework/math/statistics/cdfsampler.h
  framework/mesh/io/gmsh_io.cc
  framework/mesh/io/obj_io.cc
  framework/mesh/io/vtk_io.cc
  framework/mesh/mesh_face.h
  framework/mesh/mesh_generator/extruder_mesh_generator.cc
  framework/mesh/mesh_generator/mesh_generator.cc
  framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/mesh/surface_mesh/surface_mesh.h
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
  lua/framework/math/quadratures/sldfesq/create_sldfesq_quadrature.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
  lua/framework/mesh/surface_mesh/surface_mesh.cc
Labels: maintenance

#324 Forcing the use of node16 for regressions workflow.
  .github/workflows/builds.yaml
  .github/workflows/regression.yaml
  .github/workflows/weekly.yaml
Labels: maintenance

#326 Fixing unsed variable warnings from Apple clang v15.0.0
  framework/event_system/event_publisher.cc
  framework/math/statistics/cdfsampler.cc
  framework/mesh/raytrace/raytracer.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/scheduler/sweep_scheduler.cc
Labels: maintenance

#327 Updating configure_dependencies.py to PETSc 3.20.6
  resources/configure_dependencies.py
Labels: maintenance

#329 gha: update action versions
  .github/workflows/gh-pages.yml
  .github/workflows/qa.yaml
Labels: maintenance

#323 Bug fixes for multi-groupset, k-eigenvalue problems with reflecting boundaries
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Labels: bug-fix

#322 Improved volumetric source
  framework/math/functions/function.cc
  framework/math/functions/function.h
  framework/math/functions/scalar_material_function.cc
  framework/math/functions/scalar_material_function.h
  framework/math/functions/scalar_spatial_function.cc
  framework/math/functions/scalar_spatial_function.h
  framework/math/functions/scalar_spatial_material_function.cc
  framework/math/functions/scalar_spatial_material_function.h
  framework/math/functions/spatial_material_function.cc
  framework/math/functions/vector_spatial_function.h
  framework/math/functions/vector_spatial_material_function.h
  lua/framework/math/functions/lua_vector_spatial_function.cc
  lua/framework/math/functions/lua_vector_spatial_function.h
  lua/framework/math/functions/lua_vector_spatial_material_function.cc
  lua/framework/math/functions/lua_vector_spatial_material_function.h
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_lua_utils.h
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_sources.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/distributed_source/distributed_source.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.h
  modules/linear_boltzmann_solvers/lbs_solver/volumetric_source/volumetric_source.cc
  modules/linear_boltzmann_solvers/lbs_solver/volumetric_source/volumetric_source.h
  modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.cc
  modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.h
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_1.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_2.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3.lua
Labels: enhancement
