Repository Open-Sn/opensn, pull requests merged in 2024-03, with the labels that each got.

#160 Updating regression workflow to use PETSc-3.17.5.
  .github/workflows/Regression.yaml
Labels: maintenance

#153 Cell-wise densities
  modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/nl_keigen_acc_residual_func.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/nl_keigen_ags_residual_func.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen1.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen2.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_context.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_linear_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_structs.h
  modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/source_function.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/source_function.h
  modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/transient_source_function.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/transient_source_function.h
  modules/linear_boltzmann_solvers/b_diffusion_dfem_solver/lbs_mip_solver.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
  modules/linear_boltzmann_solvers/c_discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h
  modules/linear_boltzmann_solvers/d_do_transient/lbts_transient_solver.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.cc
Labels: enhancement

#162 Minor fixes to support updated versions of PETSc.
  framework/physics/physics_utils.cc
Labels: small fix/improvement

#163 General cleanup of sweep infrastructure. Minor refactoring of AngleAggregation class.
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/angle_aggregation/angle_aggregation.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/angle_aggregation/angle_aggregation.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/angle_set/angle_set.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/communicate_location_dependencies.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/print_sweep_ordering.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/spds/cbc_spds.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/spds/cbc_spds.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/spds/spds.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/spls/spls.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/sweep.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep/sweep_scheduler/sweep_scheduler.cc
Labels: maintenance

#166 Removing garbage from `tutorials`
  tutorials/lbs/angular_quad/qdata_na1_np4.csv
  tutorials/lbs/angular_quad/qdata_na2_np4.csv
  tutorials/lbs/first/first_example.pvtu
  tutorials/lbs/first/first_example_0.vtu
  tutorials/lbs/first/first_example_1.vtu
  tutorials/lbs/first/first_example_2.vtu
  tutorials/lbs/first/first_example_3.vtu
  tutorials/lbs/meshing/Triangle_1542_mesh_only.pvtu
  tutorials/lbs/meshing/Triangle_1542_mesh_only_0.vtu
  tutorials/lbs/meshing/Triangle_1542_mesh_only_1.vtu
  tutorials/lbs/meshing/Triangle_1542_mesh_only_2.vtu
  tutorials/lbs/meshing/Triangle_1542_mesh_only_3.vtu
  tutorials/lbs/meshing/read_obj.pvtu
  tutorials/lbs/meshing/read_obj_0.vtu
  tutorials/lbs/meshing/read_obj_1.vtu
  tutorials/lbs/meshing/read_obj_2.vtu
  tutorials/lbs/meshing/read_obj_3.vtu
Labels: maintenance

#172 Initializing several PETSc objects in LinearSolver class
  framework/math/linear_solver/linear_solver.h
Labels: bug-fix

#174 Decimal numbers are written with both whole and fraction part
  doc/coding_standard.md
  framework/math/math.cc
  framework/math/math_mpi.cc
  framework/math/quadratures/conical/quadrature_conical.cc
  framework/math/quadratures/jacobi/quadrature_jacobi.cc
  framework/math/quadratures/quadrature_tetrahedron.cc
  framework/math/quadratures/quadrature_triangle.cc
  modules/cfem_diffusion/cfem_diffusion_bndry.h
  modules/cfem_diffusion/cfem_diffusion_solver.cc
  modules/dfem_diffusion/dfem_diffusion_bndry.h
  modules/dfem_diffusion/dfem_diffusion_solver.cc
  modules/fv_diffusion/fv_diffusion_bndry.h
  modules/fv_diffusion/fv_diffusion_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
Labels: maintenance

#175 Improving tests
  test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
  test/framework/math/spatial_discretization/cg/tests.json
  test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
  test/framework/math/spatial_discretization/dg/tests.json
  test/framework/tutorials/fv_test1.cc
  test/framework/tutorials/fv_test2.cc
  test/framework/tutorials/pwlc_test1.cc
  test/framework/tutorials/pwlc_test2.cc
  test/framework/tutorials/tests.json
Labels: maintenance

#177 Adding install target
  CMakeLists.txt
  cmake/OpenSnConfig.cmake.in
  lua/CMakeLists.txt
Labels: enhancement

#178 Removing `in_` prefix from function argument names
  framework/graphs/directed_graph.h
  framework/graphs/directed_graph_vertex.h
  framework/logging/log.h
  framework/math/golub_fischer/golub_fischer.cc
  framework/math/golub_fischer/golub_fischer.h
  framework/math/petsc_utils/petsc_utils.cc
  framework/math/petsc_utils/petsc_utils.h
  framework/math/quadratures/angular_product_quadrature.cc
  framework/math/quadratures/angular_product_quadrature.h
  framework/math/quadratures/angular_quadrature_base.cc
  framework/math/quadratures/angular_quadrature_base.h
  framework/math/quadratures/quadrature.cc
  framework/math/quadratures/quadrature.h
  framework/math/quadratures/quadrature_gausslegendre.cc
  framework/math/quadratures/quadrature_gausslegendre.h
  framework/math/quadratures/quadrature_line.h
  framework/math/quadratures/sldfesq/sldfe_sq.h
  framework/math/sparse_matrix/math_sparse_matrix.cc
  framework/math/sparse_matrix/math_sparse_matrix.h
  framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_continuous.cc
  framework/math/spatial_discretization/finite_volume/finite_volume.cc
  framework/math/spatial_discretization/finite_volume/finite_volume.h
  framework/math/statistics/cdfsampler.cc
  framework/math/statistics/cdfsampler.h
  framework/math/unknown_manager/unknown_manager.cc
  framework/math/unknown_manager/unknown_manager.h
  framework/memory_usage.h
  framework/mesh/cell/cell.h
  framework/mesh/mesh_continuum/mesh_continuum_global_cell_handler.h
  framework/mesh/mesh_continuum/mesh_continuum_local_cell_handler.h
  framework/mesh/raytrace/raytracer.h
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
  framework/parameters/parameter_block.h
  framework/physics/basic_options/basic_options.h
  framework/physics/physics_material/material_property_base.h
  framework/physics/solver_base/solver.cc
  framework/physics/solver_base/solver.h
  modules/cfem_diffusion/cfem_diffusion_solver.cc
  modules/cfem_diffusion/cfem_diffusion_solver.h
  modules/dfem_diffusion/dfem_diffusion_solver.cc
  modules/dfem_diffusion/dfem_diffusion_solver.h
  modules/fv_diffusion/fv_diffusion_solver.cc
  modules/fv_diffusion/fv_diffusion_solver.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_set/aah_angle_set.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/scheduler/sweep_scheduler.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/scheduler/sweep_scheduler.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
  modules/mg_diffusion/mg_diffusion_solver.cc
  modules/mg_diffusion/mg_diffusion_solver.h
Labels: maintenance

#176 Use OpenSn elapsed time for regression test reporting
  framework/utils/timer.cc
  lua/framework/lua_app.cc
  lua/framework/lua_app.h
  test/framework/post_processors/gold/solver_info_01.lua.gold
  test/framework/post_processors/gold/solver_info_02.lua.gold
  test/framework/post_processors/tests.json
  test/src/checks.py
  test/src/test_slot.py
Labels: enhancement

#179 Refactoring sweep communicators.
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_common_lua_functions.h
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_lua_utils.cc
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_set_property.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_set/aah_angle_set.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_set/aah_angle_set.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/async_comm.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/cbc_async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/cbc_async_comm.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
Labels: maintenance

#184 Updating tests to check convergence and solution norm
  test/modules/linear_boltzmann_solvers/dsa/tests.json
Labels: maintenance

#186 Adding CMake option to optimize for build architecture
  CMakeLists.txt
Labels: small fix/improvement

#187 More in-depth refactoring of AAH sweep communicator
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
Labels: maintenance

#188 Adding missing namespace
  lua/framework/math/quadratures/angular_quadrature_polar_opt.cc
  lua/framework/math/quadratures/create_angular_quadrature.cc
  lua/framework/math/quadratures/create_curvilinear_product_quadrature.cc
  lua/framework/math/quadratures/create_line_quadrature.cc
  lua/framework/math/quadratures/create_prod_quadrature.cc
  lua/framework/math/quadratures/get_prod_quadrature.cc
  lua/framework/math/quadratures/legendre_poly/legendre_lua.cc
  lua/framework/math/quadratures/legendre_poly/legendre_lua.h
  lua/framework/math/quadratures/quadratures_lua.h
  lua/framework/math/quadratures/sldfesq/create_sldfesq_quadrature.cc
  lua/framework/math/quadratures/sldfesq/locally_refine_sldfesq.cc
  lua/framework/math/quadratures/sldfesq/sldfe_lua.h
  lua/framework/mesh/export/lua_mesh_export.cc
  lua/framework/mesh/export/lua_mesh_export.h
  lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_export.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_get_value.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_lua.h
  lua/framework/mesh/field_function_interpolation/ffinterpol_operations.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_set_property.cc
  lua/framework/mesh/ortho_grids/lua_mesh_ortho_macros.cc
  lua/framework/mesh/ortho_grids/lua_mesh_ortho_macros.h
  lua/framework/mesh/surface_mesh/lua_surface_mesh.cc
  lua/framework/mesh/surface_mesh/lua_surface_mesh.h
  lua/framework/physics/field_function/field_functions_lua.h
  lua/framework/physics/field_function/physics_export_field_func.cc
  lua/framework/physics/field_function/physics_get_field_func_list.cc
  lua/framework/physics/lua_material.cc
  lua/framework/physics/lua_material.h
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.h
  lua/modules/cfem_diffusion/lua_cfem_diff_solver.cc
  lua/modules/cfem_diffusion/lua_cfem_diff_solver.h
  lua/modules/dfem_diffusion/lua_dfem_diff_solver.cc
  lua/modules/dfem_diffusion/lua_dfem_diff_solver.h
  lua/modules/fv_diffusion/lua_fv_diff_solver.cc
  lua/modules/fv_diffusion/lua_fv_diff_solver.h
  lua/modules/mg_diffusion/lua_mg_diff_solver.cc
  lua/modules/mg_diffusion/lua_mg_diff_solver.h
Labels: maintenance

#195 Correcting the CXX_FLAGS condition for Native build
  CMakeLists.txt
Labels: bug-fix
