Repository Open-Sn/opensn, pull requests merged in 2024-04, with the labels that each got.

#193 Pass correct handle into `aquad.OptimizeForPolarSymmetry`
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
Labels: maintenance

#194 Removing obsolete API `logvol.Create`
  lua/framework/mesh/logical_volume/lua_logic_volume.cc
  lua/framework/mesh/logical_volume/lua_logic_volume.h
  lua/framework/mesh/surface_mesh/lua_surface_mesh.h
  tutorials/Tutorial01.lua
  tutorials/Tutorial02.lua
  tutorials/Tutorial03.lua
  tutorials/Tutorial04_PWLD_Diff.lua
Labels: maintenance

#201 Updating mpicpp-lite
  external/mpicpp-lite/impl/Group.h
Labels: bug-fix

#204 Using cxxopts package for cli.
  external/cxxopts/cxxopts.h
  framework/utils/utils.cc
  framework/utils/utils.h
  lua/framework/interfaces/plugin.cc
  lua/framework/lua_app.cc
  lua/framework/lua_app.h
  test/framework/post_processors/gold/solver_info_01.lua.gold
  test/framework/post_processors/gold/solver_info_02.lua.gold
  test/framework/post_processors/tests.json
Labels: enhancement

#206 Fixing minor issues with configure_dependencies.py
  resources/configure_dependencies.py
Labels: bug-fix

#211 Minor memory fixes. Cleaning up some unused code and cruft.
  framework/math/math_mpi.cc
  framework/math/math_mpi.h
  framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/physics/physics_material/multi_group_xs/single_state_mgxs.cc
Labels: maintenance, bug-fix

#212 Improving error handling of invalid Lua arguments
  lua/framework/exceptions/invalid_lua_argument.cc
  lua/framework/exceptions/invalid_lua_argument.h
  lua/framework/lua.h
  lua/framework/lua_app.cc
  test/example/example_test.lua
  test/example/tests.json
  test/lua/error_handling/functions.cc
  test/lua/error_handling/not_enough_args_1.lua
  test/lua/error_handling/not_enough_args_2.lua
  test/lua/error_handling/tests.json
  test/lua/error_handling/unexpected_arg_value_1.lua
  test/lua/error_handling/unexpected_arg_value_2.lua
  test/lua/error_handling/unexpected_arg_value_3.lua
  test/lua/error_handling/unexpected_arg_value_4.lua
  test/lua/function_wrapper/function_wrapper.cc
  test/lua/function_wrapper/function_wrapper.lua
  test/lua/function_wrapper/tests.json
Labels: enhancement

#215 Removing positional arguments from CLI
  lua/framework/lua_app.cc
  test/src/test_slot.py
Labels: enhancement

#214 Refactoring XS classes
  framework/physics/physics_material/material_property_base.cc
  framework/physics/physics_material/multi_group_xs/adjoint_mgxs.cc
  framework/physics/physics_material/multi_group_xs/adjoint_mgxs.h
  framework/physics/physics_material/multi_group_xs/multi_group_xs.cc
  framework/physics/physics_material/multi_group_xs/multi_group_xs.h
  framework/physics/physics_material/multi_group_xs/opensn_export.cc
  framework/physics/physics_material/multi_group_xs/opensn_import.cc
  framework/physics/physics_material/multi_group_xs/single_state_mgxs.h
  framework/physics/physics_namespace.h
  lua/framework/physics/lua_material.cc
  lua/framework/physics/lua_material.h
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.h
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/acceleration.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.h
  test/framework/tutorials/tutorial_06_wdd.cc
  test/framework/tutorials/tutorial_91a_pwld.cc
  test/framework/tutorials/tutorial_93_raytracing.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_1.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_2.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3_mat1.xs
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3_mat2.xs
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_4_dsa_ortho_inf.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_leakage.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4b_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_1_monoenergetic.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_2_multigroup.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_2_multigroup.xs
Labels: maintenance

#221 Removing unused `framework/materials` and replacing it with `framework/physics/physics_material`
  framework/materials/mat_prop_scalarfuncXYZTV.cc
  framework/materials/mat_prop_scalarfuncXYZTV.h
  framework/materials/material.cc
  framework/materials/material.h
  framework/materials/material_property.cc
  framework/materials/material_property.h
  framework/materials/material_property_isotropic_mg_src.h
  framework/materials/material_property_scalar_value.h
  framework/materials/multi_group_xs/multi_group_xs.cc
  framework/materials/multi_group_xs/multi_group_xs.h
  framework/materials/multi_group_xs/opensn_export.cc
  framework/materials/multi_group_xs/opensn_import.cc
  framework/math/petsc_utils/petsc_utils.cc
  framework/math/petsc_utils/petsc_utils.h
  framework/physics/physics_material/material_property_base.h
  framework/physics/physics_material/material_property_isotropic_mg_src.h
  framework/physics/physics_material/physics_material.h
  framework/physics/physics_namespace.h
  framework/physics/physics_utils.cc
  framework/physics/solver_base/solver.h
  framework/runtime.cc
  lua/framework/physics/lua_material.cc
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/acceleration.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/energy_collapse.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.h
  modules/mg_diffusion/mg_diffusion_solver.cc
  modules/mg_diffusion/mg_diffusion_solver.h
  test/framework/tutorials/tutorial_06_wdd.cc
  test/framework/tutorials/tutorial_91a_pwld.cc
Labels: maintenance

#223 Fixes for GCC 13.x
  framework/utils/utils.h
Labels: bug-fix

#225 Updating regression ci workflow. Adding build test workflow.
  .github/workflows/builds.yaml
  .github/workflows/regression.yaml
  CMakeLists.txt
Labels: maintenance

#227 Adding missing colon for nightly build test workflow
  .github/workflows/builds.yaml
Labels: bug-fix

#228 Updating bagdes
  README.md
Labels: maintenance

#226 Adding file/line info to additional Lua error messages.
  lua/framework/lua.cc
  lua/framework/lua.h
  lua/framework/physics/lua_material.cc
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
Labels: maintenance

#210 Initial Support for OpenMC MGXS Libraries
  CMakeLists.txt
  framework/materials/material.h
  framework/materials/multi_group_xs/multi_group_xs.h
  framework/materials/multi_group_xs/openmc_import.cc
  framework/materials/multi_group_xs/opensn_export.cc
  framework/materials/multi_group_xs/opensn_import.cc
  framework/math/sparse_matrix/math_sparse_matrix.h
  framework/utils/hdf_utils.h
  lua/framework/physics/lua_material.cc
  lua/framework/physics/lua_material.h
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
  lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.h
  lua/modules/linear_bolzmann_solvers/do_transient/lbts_lua_set_property.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/energy_collapse.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  resources/configure_dependencies.py
  test/CMakeLists.txt
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_cset.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
  test/modules/linear_boltzmann_solvers/transport_keigen/u235.h5
  test/modules/linear_boltzmann_solvers/transport_keigen/uo2.h5
Labels: enhancement

#236 Fixing indentation in configure_dependencies.py
  resources/configure_dependencies.py
Labels: bug-fix

#233 Throw an exception if we generate a partition with zero cells
  framework/mesh/mesh_generator/mesh_generator.cc
Labels: bug-fix
