Repository Open-Sn/opensn, pull requests merged in 2024-08, with the labels that each got.

#336 Refactoring regression test scripts
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_jfnk.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_scdsa.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_smm.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/tests.json
  test/run_tests
  test/src/checks.py
  test/src/job_manager.py
  test/src/test_slot.py
Labels: small fix/improvement, bug-fix

#325 Refactor AGS solver
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/executors/lbs_steady_state.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.h
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_context.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_context.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_linear_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_linear_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/power_iteration_keigen.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
  test/modules/linear_boltzmann_solvers/transport_steady/simple_upscatter.xs
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_ags_upscatter.lua
Labels: maintenance

#341 Adding multi-platform support for properly escaping Lua argument strings in `run_tests`
  test/src/test_slot.py
Labels: bug-fix

#347 Forcing some multi-groupset tests to use only 1 AGS iteration
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4b_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
Labels: maintenance

#354 Store K tensor as NDArray
  modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_smm.h
Labels: enhancement

#335 Adding Classic Richardson WGS Solver
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_lua_utils.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/lbs_iterative_methods.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_UO2_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/reed_balance_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2_crichardson.lua
Labels: enhancement
