Repository Open-Sn/opensn, pull requests merged in 2024-11, with the labels that each got.

#393 Cleaning up use of PETSc iterative method names
  framework/math/linear_solver/linear_solver.cc
  framework/math/linear_solver/linear_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.cc
Labels: bug-fix

#400 Sweep chunk zeroing bug
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
  modules/linear_boltzmann_solvers/lbs_solver/io/flux_moments_io.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
Labels: bug-fix

#405 Fixing compiler warnings in Gmsh io routines
  framework/mesh/io/gmsh_io_v22.cc
  framework/mesh/io/gmsh_io_v41.cc
Labels: maintenance

#408 Removing deprecated adjoint solver and related files
  framework/math/math_tensor_rnx.h
  framework/math/math_vector_nx.h
  lua/modules/linear_bolzmann_solvers/discrete_ordinates_adjoint_solver/lbsadj_lua_export_impmap_binary.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.h
Labels: maintenance

#407 Removing dead arbitrary boundary code and regression test
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/boundary/arbitrary_boundary.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/boundary/arbitrary_boundary.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
Labels: maintenance

#404 Refactoring LinearSolver and NonLinearSolver
  framework/math/linear_solver/linear_matrix_action_Ax.cc
  framework/math/linear_solver/linear_matrix_action_Ax.h
  framework/math/linear_solver/linear_solver.cc
  framework/math/linear_solver/linear_solver.h
  framework/math/linear_solver/petsc_linear_solver.cc
  framework/math/linear_solver/petsc_linear_solver.h
  framework/math/linear_solver/preconditioner_apply.cc
  framework/math/linear_solver/preconditioner_apply.h
  framework/math/linear_solver/preconditioner_context.h
  framework/math/nonlinear_solver/nonlinear_solver.h
  framework/math/nonlinear_solver/nonlinear_solver_options.h
  framework/math/nonlinear_solver/petsc_nonlinear_solver.cc
  framework/math/nonlinear_solver/petsc_nonlinear_solver.h
  framework/math/nonlinear_solver/petsc_nonlinear_solver_options.cc
  framework/math/nonlinear_solver/petsc_nonlinear_solver_options.h
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Labels: maintenance

#411 Improving performance of assembling routines in `DiffusionPWLCSolver` and `DiffusionMIPSolver`
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_mip_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_pwlc_solver.cc
Labels: enhancement

#402 WGS Context Cleanup
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.cc
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.h
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.h
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.h
Labels: maintenance

#397 Simplifying SPLS implementation. Creating levelized SPLS.
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/aah.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/cbc.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/sweep.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
Labels: enhancement, maintenance

#406 Adding additional checks to nightly sanitizer test
  .github/workflows/builds.yaml
  CMakePresets.json
  tools/developer/ignorelist.txt
Labels: maintenance

#412 Fix GCC compiler warnings for MeshContinuum and NDArray classes
  framework/data_types/ndarray.h
  framework/mesh/mesh_continuum/mesh_continuum.cc
  framework/mesh/mesh_continuum/mesh_continuum.h
Labels: maintenance

#415 Updating coding standards for conditionals and getters/setters
  doc/coding_standard.md
Labels: documentation

#427 SCDSA-AAH + Multi-Sweep Fixes
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
  test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock.lua
Labels: maintenance

#410 Simple partition rebalancing
  framework/mesh/mesh_generator/mesh_generator.cc
  framework/mesh/mesh_generator/mesh_generator.h
Labels: enhancement

#377 Fixing conditions that decide `FaceOrientation`
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.cc
Labels: bug-fix

#425 Creating LBSSolverVecOps class for group-scoped vector operations
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.h
  modules/linear_boltzmann_solvers/executors/nl_keigen.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
  modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
  modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_residual_func.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.cc
  modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_vecops.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_vecops.h
  modules/linear_boltzmann_solvers/lbs_solver/preconditioning/lbs_dsa_preconditioner.cc
  modules/linear_boltzmann_solvers/lbs_solver/preconditioning/lbsmip_tgdsa_preconditioner.cc
Labels: maintenance
