Repository Open-Sn/opensn, pull requests merged in 2024-02, with the labels that each got.

#100 Adjoint Option
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_init_materials.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_structs.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.h
  modules/linear_boltzmann_solvers/executors/lbs_steady_state.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_1b_adjoint.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_2b_adjoint.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_3b_adjoint.lua
Labels: enhancement

#108 Moving field functions in their own location
  framework/field_functions/field_function.cc
  framework/field_functions/field_function.h
  framework/field_functions/field_function_grid_based.cc
  framework/field_functions/field_function_grid_based.h
  framework/field_functions/field_function_interface.cc
  framework/field_functions/field_function_interface.h
  framework/field_functions/grid_based_field_function_interface.cc
  framework/field_functions/grid_based_field_function_interface.h
  framework/field_functions/interpolation/ffinter_line.cc
  framework/field_functions/interpolation/ffinter_line.h
  framework/field_functions/interpolation/ffinter_point.cc
  framework/field_functions/interpolation/ffinter_point.h
  framework/field_functions/interpolation/ffinter_slice.cc
  framework/field_functions/interpolation/ffinter_slice.h
  framework/field_functions/interpolation/ffinter_volume.cc
  framework/field_functions/interpolation/ffinter_volume.h
  framework/field_functions/interpolation/ffinterpolation.h
  framework/field_functions/operations/field_copy.cc
  framework/field_functions/operations/field_copy.h
  framework/field_functions/operations/field_operation.cc
  framework/field_functions/operations/field_operation.h
  framework/field_functions/operations/multi_field.cc
  framework/field_functions/operations/multi_field.h
  framework/field_functions/operations/partitioner_predicate.cc
  framework/field_functions/operations/partitioner_predicate.h
  framework/post_processors/aggregate_nodal_value_post_processor.cc
  framework/post_processors/aggregate_nodal_value_post_processor.h
  framework/post_processors/cell_volume_integral_post_processor.cc
  framework/post_processors/cell_volume_integral_post_processor.h
  lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_export.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_get_value.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_operations.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_set_property.cc
  lua/framework/physics/field_function/physics_export_field_func.cc
  lua/framework/physics/field_function/physics_get_field_func_list.cc
  lua/framework/physics/field_operations/field_ops_lua.cc
  lua/framework/physics/solver_base/physics_solver_lua_utils.cc
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_get_field_funcs.cc
  modules/cfem_diffusion/cfem_diffusion_solver.cc
  modules/dfem_diffusion/dfem_diffusion_solver.cc
  modules/fv_diffusion/fv_diffusion_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
  test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
  test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
  test/framework/tutorials/fv_test1.cc
  test/framework/tutorials/fv_test2.cc
  test/framework/tutorials/pwlc_test1.cc
  test/framework/tutorials/pwlc_test2.cc
  test/framework/tutorials/tutorial_06_wdd.cc
  test/framework/tutorials/tutorial_91a_pwld.cc
  test/framework/tutorials/tutorial_93_raytracing.cc
  test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
  test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.cc
Labels: maintenance

#110 Removing references to ChiTech
  framework/mesh/mesh_continuum/mesh_continuum.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
  lua/framework/logging/log.cc
  lua/framework/utils/lua_exit.cc
Labels: maintenance

#107 Adding coding standard page into doco
  doc/coding_standard.md
  doc/index.rst
Labels: documentation

#112 Physics directory reorganization, pt1
  framework/event_system/physics_event_publisher.cc
  framework/event_system/physics_event_publisher.h
  framework/physics/physics_material/material_property_base.h
  framework/physics/physics_material/material_property_isotropic_mg_src.h
  framework/physics/physics_material/material_property_scalar_value.h
  framework/physics/physics_material/multi_group_xs/multi_group_xs.h
  framework/physics/physics_material/physics_material.h
  framework/post_processors/post_processor.cc
  lua/framework/physics/physics_material_properties.cc
  lua/framework/physics/solver_base/physics_solver_lua_utils.cc
  modules/point_reactor_kinetics/point_reactor_kinetics.cc
Labels: maintenance

#114 Using operators `and`, `or`, and `not` in boolean operations
  framework/event_system/event.cc
  framework/field_functions/interpolation/ffinter_line.cc
  framework/field_functions/interpolation/ffinter_slice.cc
  framework/logging/log.cc
  framework/logging/log_stream.cc
  framework/math/math.cc
  framework/math/quadratures/cylindrical_angular_quadrature.cc
  framework/math/quadratures/jacobi/quadrature_jacobi.cc
  framework/math/quadratures/spherical_angular_quadrature.cc
  framework/math/sparse_matrix/math_sparse_matrix.cc
  framework/math/spatial_discretization/cell_mappings/piecewise_linear/piecewise_linear_polygon_mapping.cc
  framework/math/spatial_discretization/cell_mappings/piecewise_linear/piecewise_linear_slab_mapping.cc
  framework/math/spatial_discretization/finite_element/lagrange/lagrange_discontinuous.cc
  framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_discontinuous.cc
  framework/math/statistics/cdfsampler.cc
  framework/mesh/logical_volume/surface_mesh_logical_volume.cc
  framework/mesh/mesh_continuum/grid_vtk_utils.cc
  framework/mesh/mesh_continuum/mesh_continuum.cc
  framework/mesh/raytrace/raytracer.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/mesh/sweep_utilities/angle_set/aah_angle_set.cc
  framework/mesh/sweep_utilities/communicators/aah_asyn_comm.cc
  framework/mesh/sweep_utilities/fluds/aah_fluds.cc
  framework/mesh/sweep_utilities/fluds/aah_fluds_common_data.cc
  framework/mesh/sweep_utilities/sweep_boundary/boundary_reflecting.cc
  framework/mesh/sweep_utilities/sweep_scheduler/sweep_scheduler.cc
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
  framework/mesh/volume_mesher/volume_mesher.cc
  lua/framework/mesh/field_function_interpolation/ffinterpol_set_property.cc
  lua/framework/mesh/surface_mesh/surface_mesh_check_cycles.cc
  lua/framework/mesh/volume_mesher/volume_mesher_set_property.cc
  lua/framework/physics/physics_material_properties.cc
  lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_set_property.cc
  modules/dfem_diffusion/dfem_diffusion_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/diffusion_mip_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/groupset/lbs_groupset.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_convergence_test.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/d_do_transient/sweep_chunks/lbts_sweep_chunk_pwl.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
  test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
  test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
Labels: maintenance

#128 Replacing `PETSC_COMM_WORLD` with `opensn::mpi_comm`
  framework/math/linear_solver/linear_solver.cc
  framework/math/petsc_utils/petsc_utils.cc
  framework/math/petsc_utils/petsc_utils.h
  lua/framework/lua_app.cc
  modules/dfem_diffusion/dfem_diffusion_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/diffusion.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/ags_linear_solver.cc
  modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_linear_solver.cc
  modules/mg_diffusion/mg_diffusion_solver.cc
Labels: maintenance

#127 Minor fixes for Clang warnings.
  framework/field_functions/interpolation/ffinter_line.h
  framework/field_functions/interpolation/ffinter_point.h
  framework/field_functions/interpolation/ffinter_slice.h
  framework/field_functions/interpolation/ffinter_volume.h
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h
Labels: maintenance

#129 Response Evaluator
  lua/modules/linear_bolzmann_solvers/response_evaluator/response_evaluator.cc
  lua/modules/linear_bolzmann_solvers/response_evaluator/response_evaluator.h
  modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
  modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.cc
  modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.h
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_1b_adjoint.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_1c_response.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_2b_adjoint.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_2c_response.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_3a_forward.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_3b_adjoint.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_3c_response.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_1.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_2.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3.lua
  test/modules/linear_boltzmann_solvers/transport_adjoint/tests.json
Labels: enhancement

#130 Refactoring AAH and CBC sweep chunks
  framework/mesh/sweep_utilities/sweep_chunk_base.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h
Labels: maintenance

#138 Allow optional space between -- and ]] when parsing lua files with doco
  doc/scripts/lua2md.py
Labels: bug-fix

#139 Properly detect and use python interpreter in the doco generation
  doc/CMakeLists.txt
Labels: bug-fix

#134 Bug fixes for PWLRZ sweepchunk. Minor renaming across sweep chunks.
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.h
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.cc
  modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
  modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h
Labels: bug-fix

#145 Fixing file export in parallel
  framework/field_functions/field_function_grid_based.cc
  framework/mesh/mesh_continuum/mesh_continuum.cc
Labels: bug-fix

#146 Removing API to create vertices and cells from LUA layer
  lua/framework/mesh/unpartitioned_mesh/basic_operations.cc
  lua/framework/mesh/unpartitioned_mesh/unpartition_mesh_lua_utils.h
Labels: maintenance

#148 Do not manipulate directory name with extracted sources in configure_dependencies.py
  resources/configure_dependencies.py
Labels: bug-fix

#144 Adding input path to runtime. Changing default split mesh file prefix.
  framework/mesh/mesh_generator/split_file_mesh_generator.cc
  framework/mesh/mesh_generator/split_file_mesh_generator.h
  framework/runtime.cc
  framework/runtime.h
  lua/framework/lua_app.cc
  lua/framework/lua_app.h
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
Labels: bug-fix

#158 Updating coding standards with #include rules
  doc/coding_standard.md
Labels: documentation, enhancement
