Repository Open-Sn/opensn, pull requests merged in 2025-04, with the labels that each got.

#570 Python testing updates
  python/lib/console.cc
  test/python/framework/post_processors/solver_info_01.py
  test/python/framework/post_processors/solver_info_02.py
  test/python/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.py
  test/src/job_manager.py
  test/src/test_slot.py
  tools/developer/lsan.supp
Labels: maintenance

#571 Promoting Python interface to primary and updating workflows.
  .github/workflows/builds.yaml
  .github/workflows/gh-pages.yml
  .github/workflows/regression.yaml
  .github/workflows/weekly.yaml
  CMakeLists.txt
Labels: maintenance

#572 Disabling Python interface if Lua interface is requested.
  CMakeLists.txt
Labels: bug-fix

#578 Suppressing colorized log output when using the Python module
  pyopensn/py_env.cc
Labels: bug-fix

#579 Restoring function stack for the Lua interface and update Lua inputs
  framework/runtime.cc
  framework/runtime.h
  test/lua/framework/tutorials/tutorial_93_raytracing.lua
  test/lua/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.lua
  test/lua/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.lua
Labels: bug-fix

#580 Flushing standard streams and synchronizing in Finalize.
  framework/runtime.cc
Labels: bug-fix

#582 fixing documentation plain text for XS API
  python/lib/xs.cc
Labels: maintenance

#581 Remove Gmsh files from Linguist
  .gitattributes
Labels: maintenance

#585 Updating LSAN suppressions for better Python coverage
  tools/developer/lsan.supp
Labels: maintenance

#587 Falling back to module mode if find_package(Boost CONFIG) fails
  CMakeLists.txt
Labels: maintenance

#589 Bind quadrature member variables
  lua/lib/opensn.cc
  lua/lib/types.h
  python/lib/aquad.cc
  python/lib/py_app.cc
  python/lib/py_wrappers.h
  test/lua/framework/math/quadrature/gold/prod_quad_1d_slab.lua.gold
  test/lua/framework/math/quadrature/gold/prod_quad_2d_xy.lua.gold
  test/lua/framework/math/quadrature/gold/prod_quad_3d_xyz.lua.gold
  test/lua/framework/math/quadrature/prod_quad_1d_slab.lua
  test/lua/framework/math/quadrature/prod_quad_2d_xy.lua
  test/lua/framework/math/quadrature/prod_quad_3d_xyz.lua
  test/lua/framework/math/quadrature/tests.json
  test/python/framework/math/quadrature/gold/prod_quad_1d_slab.py.gold
  test/python/framework/math/quadrature/gold/prod_quad_2d_xy.py.gold
  test/python/framework/math/quadrature/gold/prod_quad_3d_xyz.py.gold
  test/python/framework/math/quadrature/prod_quad_1d_slab.py
  test/python/framework/math/quadrature/prod_quad_2d_xy.py
  test/python/framework/math/quadrature/prod_quad_3d_xyz.py
  test/python/framework/math/quadrature/tests.json
Labels: enhancement

#595 Temporarily removing tutorials from sanitizer workflow
  .github/workflows/builds.yaml
  test/src/test_slot.py
Labels: maintenance

#593 Fixing an issue where we erroneously appended a ANSI reset sequence after every call to log
  framework/logging/log.cc
  framework/logging/log_stream.h
Labels: bug-fix

#598 Fixing install target for lua
  CMakeLists.txt
  lua/CMakeLists.txt
Labels: enhancement, bug-fix

#607 adding images folder for aquad
  doc/CMakeLists.txt
Labels: bug-fix

#605 Removing block id remapping for Gmsh meshes
  framework/mesh/io/gmsh_io_v22.cc
  framework/mesh/io/gmsh_io_v41.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v2.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v4.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v2.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v4.py
Labels: maintenance

#555 Refactoring the interface between sweep chunks and the sweep scheduler
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/discrete_ordinates_curvilinear_problem.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/sweep_chunks/aah_sweep_chunk_rz.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/sweep_chunks/aah_sweep_chunk_rz.h
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/discrete_ordinates_problem.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/iterative_methods/sweep_wgs_context.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/angle_aggregation/angle_aggregation.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/angle_aggregation/angle_aggregation.h
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/scheduler/sweep_scheduler.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/scheduler/sweep_scheduler.h
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/aah_sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/aah_sweep_chunk.h
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/cbc_sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/cbc_sweep_chunk.h
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/sweep_chunk.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/sweep_chunk.h
Labels: maintenance

#604 Revising CUDA support to supply missing MPI headers to nvcc
  CMakeLists.txt
Labels: bug-fix

#612 Adding checks to ensure that all mesh block ids have entries in the user-supplied xs map
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
Labels: bug-fix

#613 Improving volumetric source logging.
  modules/linear_boltzmann_solvers/lbs_problem/volumetric_source/volumetric_source.cc
  modules/linear_boltzmann_solvers/lbs_problem/volumetric_source/volumetric_source.h
Labels: maintenance

#616 Removing LBS MIP DFEM diffusion solver
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.cc
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.h
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
  modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.h
  python/lib/solver.cc
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_1d_1g.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1a_qblock.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1b_qblock.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/tests.json
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/utils/qblock_materials.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_keigen/utils/qblock_mesh.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_3a_dsa_ortho.py
  test/python/modules/linear_boltzmann_solvers/mg_diffusion_steady/tests.json
Labels: maintenance

#621 Removing Lua inputs for LBS MIP diffusion solver.
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_1d_1g.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1a_qblock.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1b_qblock.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/tests.json
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/utils/qblock_materials.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_keigen/utils/qblock_mesh.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_3a_dsa_ortho.lua
  test/lua/modules/linear_boltzmann_solvers/mg_diffusion_steady/tests.json
Labels: maintenance

#622 Removing Exit() and replacing calls to it with throw
  framework/math/sparse_matrix/sparse_matrix.cc
  framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_continuous.cc
  framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_discontinuous.cc
  framework/math/unknown_manager/unknown_manager.cc
  framework/mesh/mesh_generator/split_file_mesh_generator.cc
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/parameters/input_parameters.cc
  framework/runtime.cc
  framework/runtime.h
  lua/lib/console.cc
  lua/lib/opensn.cc
  modules/diffusion/mg_diffusion_solver.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/discrete_ordinates_curvilinear_problem.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/boundary/sweep_boundary.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds_common_data.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/spds/spds.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
Labels: maintenance

#624 Updating parameter tests to reflect changes in Lua error formatting.
  lua/lib/console.cc
  test/lua/framework/parameters/tests.json
Labels: maintenance
