Repository Open-Sn/opensn, pull requests merged in 2025-08, with the labels that each got.

#703 Documentation updates
  README.md
  doc/source/devguide/coding_standard.rst
Labels: documentation

#704 Remove transient bits
  framework/math/time_integrations/crank_nicolson_time_intgr.cc
  framework/math/time_integrations/crank_nicolson_time_intgr.h
  framework/math/time_integrations/implicit_euler_time_intgr.cc
  framework/math/time_integrations/implicit_euler_time_intgr.h
  framework/math/time_integrations/theta_scheme_time_intgr.cc
  framework/math/time_integrations/theta_scheme_time_intgr.h
  framework/math/time_integrations/time_integration.cc
  framework/math/time_integrations/time_integration.h
  framework/physics/problem.cc
  framework/physics/solver.cc
  framework/physics/solver.h
  framework/physics/time_steppers/constant_time_stepper.cc
  framework/physics/time_steppers/constant_time_stepper.h
  framework/physics/time_steppers/time_stepper.cc
  framework/physics/time_steppers/time_stepper.h
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/solvers/lbs_transient.cc
  modules/linear_boltzmann_solvers/solvers/lbs_transient.h
Labels: maintenance

#709 Changing ExportMultipleToVTK() to ExportMultipleToPVTU()
  framework/field_functions/field_function_grid_based.cc
  framework/field_functions/field_function_grid_based.h
  python/lib/fieldfunc.cc
  test/python/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
  test/python/framework/math/spatial_discretization/dg/sdm_test_02_discontinuous.cc
  test/python/framework/tutorials/fv_test1.cc
  test/python/framework/tutorials/fv_test2.cc
  test/python/framework/tutorials/pwlc_test1.cc
  test/python/framework/tutorials/pwlc_test2.cc
  test/python/framework/tutorials/tutorial_06_wdd.cc
  test/python/framework/tutorials/tutorial_91a_pwld.cc
  test/python/framework/tutorials/tutorial_93_raytracing.cc
  test/python/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
  test/python/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.cc
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.py
Labels: maintenance

#711 Updates to CurvilinearQuadrature
  framework/math/quadratures/angular/curvilinear_product_quadrature.cc
  framework/math/quadratures/angular/curvilinear_product_quadrature.h
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/sweep_chunks/aah_sweep_chunk_rz.cc
  python/lib/aquad.cc
  python/lib/py_app.cc
  python/lib/py_wrappers.h
Labels: maintenance

#706 Fixing face neighbor assignment for boundary cells on unstructured meshes
  framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
Labels: bug-fix

#715 Removing debug statement
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/smm_acceleration.cc
Labels: maintenance

#716 Removing old Lua input. Deleting temporary files created during testing.
  test/python/framework/tutorials/tutorial_93_raytracing.lua
  test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part2.py
Labels: maintenance

#717 Add experimental warning to SMM. Throw an exception if SMM is used with scattering order > 0.
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/smm_acceleration.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.h
  test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_U235_smm.py
Labels: maintenance

#713 Refactoring opensn native cross-section file reader in its own class
  framework/materials/multi_group_xs/multi_group_xs.h
  framework/materials/multi_group_xs/openmc_import.cc
  framework/materials/multi_group_xs/opensn_import.cc
  framework/materials/multi_group_xs/xsfile.cc
  framework/materials/multi_group_xs/xsfile.h
  framework/utils/utils.h
  python/lib/xs.cc
  test/python/framework/tutorials/tutorial_06_wdd.cc
  test/python/framework/tutorials/tutorial_91a_pwld.cc
Labels: maintenance

#722 Updating scaling study scripts and inputs
  tools/scaling/sweep/node_to_node/unstructured_mesh/strong/generate_scaling_study.py
  tools/scaling/sweep/node_to_node/unstructured_mesh/strong/strong_scaling.py
  tools/scaling/sweep/node_to_node/unstructured_mesh/weak/generate_scaling_study.py
  tools/scaling/sweep/node_to_node/unstructured_mesh/weak/weak_scaling.py
Labels: maintenance

#726 Removing unused SetDocGroup
  framework/field_functions/field_function_grid_based.cc
  framework/graphs/kba_graph_partitioner.cc
  framework/graphs/linear_graph_partitioner.cc
  framework/graphs/petsc_graph_partitioner.cc
  framework/math/functions/piecewise_linear_1d.cc
  framework/mesh/logical_volume/boolean_logical_volume.cc
  framework/mesh/mesh_generator/distributed_mesh_generator.cc
  framework/mesh/mesh_generator/extruder_mesh_generator.cc
  framework/mesh/mesh_generator/from_file_mesh_generator.cc
  framework/mesh/mesh_generator/mesh_generator.cc
  framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
  framework/mesh/mesh_generator/split_file_mesh_generator.cc
  framework/parameters/input_parameters.h
  modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/discrete_ordinates_curvilinear_problem.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/discrete_ordinates_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/point_source/point_source.cc
  modules/linear_boltzmann_solvers/lbs_problem/volumetric_source/volumetric_source.cc
  modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.cc
  modules/linear_boltzmann_solvers/solvers/nl_keigen_solver.cc
  modules/linear_boltzmann_solvers/solvers/pi_keigen_solver.cc
  modules/linear_boltzmann_solvers/solvers/steady_state_solver.cc
Labels: maintenance

#724 Removing unused spatial_discretization LBS option
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_structs.h
  python/lib/solver.cc
  test/python/modules/linear_boltzmann_solvers/transport_steady/angular_io_1d.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/hdpe_balance.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/reed_balance.py
  test/python/modules/linear_boltzmann_solvers/transport_steady/reed_balance_crichardson.py
  test/python/modules/linear_boltzmann_solvers/transport_steady_cbc/hdpe_balance.py
Labels: maintenance

#730 Finalizing Python binding documentation
  python/lib/fieldfunc.cc
  python/lib/response.cc
  python/lib/solver.cc
Labels: documentation

#737 Avoid uncaught exceptions in main
  python/main.cc
Labels: bug-fix

#739 Convert Python default environment pointer from a raw pointer to unique_ptr
  pyopensn/py_env.cc
  pyopensn/py_module.cc
  python/lib/console.cc
  python/lib/context.cc
  python/lib/parameter.cc
  python/lib/py_app.cc
  python/lib/py_app.h
  python/lib/py_env.h
  python/lib/solver.cc
Labels: maintenance

#735 Refactoring inside `SourceFunction`
  modules/linear_boltzmann_solvers/lbs_problem/source_functions/source_function.cc
  modules/linear_boltzmann_solvers/lbs_problem/source_functions/source_function.h
  modules/linear_boltzmann_solvers/lbs_problem/source_functions/transient_source_function.cc
  modules/linear_boltzmann_solvers/lbs_problem/source_functions/transient_source_function.h
Labels: maintenance

#738 Updating quadrature documentation
  python/lib/aquad.cc
Labels: documentation

#744 Don't call `InitializeBoundaries` from a ctor
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
Labels: bug-fix
