Repository Open-Sn/opensn, pull requests merged in 2025-02, with the labels that each got.

#460 Exodusii bug fix for wedge elements
  framework/mesh/io/vtk_io.cc
  test/assets/mesh/fuel_hex.e
  test/assets/mesh/fuel_wedge.e
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_2g_exo_hex.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_2g_exo_wedge.lua
  test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
Labels: bug-fix

#479 Creating Developer's Guide section in the doco
  doc/CMakeLists.txt
  doc/devguide/coding_standard.md
  doc/devguide/index.rst
  doc/devguide/workflow.md
  doc/index.rst
Labels: documentation

#480 Adding information on how to squash commits into developer's guide
  doc/devguide/workflow.md
Labels: documentation

#478 Converting some unit tests into real unit tests
  test/framework/data_types/data_types_test_00.cc
  test/framework/data_types/gold/data_types_test_00.lua.gold
  test/framework/math/dense_matrix_test.cc
  test/framework/math/dense_matrix_test.lua
  test/framework/math/math_test_00.cc
  test/framework/math/math_test_00.lua
  test/framework/math/tests.json
  test/framework/math/vector_test.cc
  test/framework/math/vector_test.lua
  test/unit/framework/data_types/byte_array_test.cc
  test/unit/framework/data_types/ndarray_test.cc
  test/unit/framework/math/dense_matrix_test.cc
  test/unit/framework/math/sparse_matrix_test.cc
  test/unit/framework/math/vector_test.cc
Labels: maintenance

#484 Minor fix in mesh_continuum for debug builds
  framework/mesh/mesh_continuum/mesh_continuum.cc
Labels: bug-fix

#486 Fixing `#include`s in `mesh.h`
  framework/field_functions/interpolation/ffinter_line.h
  framework/field_functions/interpolation/ffinter_point.h
  framework/math/quadratures/angular/sldfe_sq_quadrature.h
  framework/math/spatial_discretization/cell_mappings/cell_mapping.cc
  framework/math/spatial_discretization/cell_mappings/cell_mapping.h
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.cc
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.h
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.h
  framework/mesh/cell/cell.cc
  framework/mesh/logical_volume/surface_mesh_logical_volume.cc
  framework/mesh/mesh.h
  framework/mesh/mesh_continuum/mesh_continuum.h
  framework/mesh/mesh_face.h
  framework/mesh/mesh_vector.cc
  framework/mesh/raytrace/raytracer.h
  framework/mesh/surface_mesh/surface_mesh.cc
  framework/mesh/surface_mesh/surface_mesh.h
  modules/diffusion/dfem_diffusion_solver.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/sweep.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
Labels: maintenance

#487 Don't append extensions to empty restart file names
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Labels: bug-fix

#489 Eliminating `squad` module
  doc/devguide/lua_bindings.md
  framework/math/quadratures/gausschebyshev_quadrature.cc
  framework/math/quadratures/gausschebyshev_quadrature.h
  framework/math/quadratures/gausslegendre_quadrature.cc
  framework/math/quadratures/gausslegendre_quadrature.h
  lua/lib/opensn.cc
  test/framework/math/quadrature/gold/quadrature_test1.lua.gold
  test/framework/math/quadrature/quadrature_test1.lua
  test/framework/math/quadrature/tests.json
  test/unit/framework/math/quadrature_test.cc
Labels: enhancement

#488 Replacing `IsotropicMultiGroupSource` with `VolumetricSource`
  framework/materials/material.cc
  framework/materials/material.h
  lua/lib/opensn.cc
  lua/lib/parse_table.cc
  modules/diffusion/mg_diffusion_solver.cc
  modules/diffusion/mg_diffusion_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
  modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
  modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
  modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
  test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/1g_infinite_pure_absorber_balance_gmres.lua
  test/modules/linear_boltzmann_solvers/transport_steady/1g_infinite_pure_absorber_balance_richardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/angular_io_1d.lua
  test/modules/linear_boltzmann_solvers/transport_steady/hdpe_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/reed_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/reed_balance_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_4_dsa_ortho_inf.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4b_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_5_poly_a_ani_hetero_bndry.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v4.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_scotch.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1a_extruder.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1b_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured_restart.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_3a_dsa_ortho.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2_crichardson.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2_restart.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6a_dist_mesh.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6a_split_mesh.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6b_dist_mesh.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6b_split_mesh.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_ags_upscatter.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v2.lua
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v4.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/hdpe_balance.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_1_monoenergetic.lua
  test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_2_multigroup.lua
  tutorials/lbs/first/first_example.lua
Labels: enhancement

#495 Adding a CMake preset for code coverage with Clang
  CMakePresets.json
Labels: enhancement

#499 Moving Matrix3x3 and Vector3 from framework/mesh to framework/math
  framework/data_types/varying.h
  framework/field_functions/interpolation/ffinter_line.h
  framework/field_functions/interpolation/ffinter_point.h
  framework/math/functions/scalar_material_function.h
  framework/math/functions/scalar_spatial_function.h
  framework/math/functions/scalar_spatial_material_function.h
  framework/math/functions/vector_spatial_function.h
  framework/math/functions/vector_spatial_material_function.h
  framework/math/matrix3x3.h
  framework/math/quadratures/angular/angular_quadrature.h
  framework/math/quadratures/angular/sldfe_sq_quadrature.cc
  framework/math/quadratures/angular/sldfe_sq_quadrature.h
  framework/math/quadratures/gauss_quadrature.h
  framework/math/spatial_discretization/cell_mappings/cell_mapping.cc
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.h
  framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.h
  framework/math/vector3.cc
  framework/math/vector3.h
  framework/mesh/cell/cell.cc
  framework/mesh/cell/cell.h
  framework/mesh/logical_volume/logical_volume.h
  framework/mesh/mesh_continuum/mesh_continuum_vertex_handler.h
  framework/mesh/mesh_face.h
  framework/mesh/raytrace/raytracer.h
  lua/lib/opensn.cc
  lua/lib/parse_table.cc
  lua/lib/types.h
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
  test/unit/framework/data_types/byte_array_test.cc
  test/unit/framework/mesh/vector3_test.cc
Labels: maintenance

#497 Adding coverage workflow and Coveralls integration to nightly builds
  .github/workflows/builds.yaml
  .github/workflows/regression.yaml
  .github/workflows/weekly.yaml
  CMakePresets.json
Labels: enhancement

#502 Adding missing `module load` to coverage workflow.
  .github/workflows/builds.yaml
Labels: bug-fix

#494 Simplifications to SweepScheduler
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/scheduler/sweep_scheduler.cc
Labels: maintenance

#493 Performance improvements for AAH_ASynchronousCommunicator
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
  modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
Labels: enhancement
