Repository Open-Sn/opensn, pull requests merged in 2025-03, with the labels that each got.

#505 Converting some more unit tests to be actual unit tests
  test/framework/graphs/gold/kba_graph_partitioner.lua.gold
  test/framework/graphs/kba_graph_partitioner.lua
  test/framework/graphs/tests.json
  test/framework/misc_utils/gold/misc_utils_test_00.lua.gold
  test/framework/misc_utils/misc_utils_test_00.cc
  test/framework/misc_utils/misc_utils_test_00.lua
  test/framework/misc_utils/tests.json
  test/framework/parameters/gold/params_test_00.lua.gold
  test/framework/parameters/params_test_00.cc
  test/unit/framework/data_types/varying_test.cc
  test/unit/framework/graphs/kba_graph_partitioner_test.cc
  test/unit/framework/misc_utils/misc_utils_test.cc
Labels: maintenance

#504 An embedded Python console for OpenSn
  .gitignore
  CMakeLists.txt
  pyopensn/CMakeLists.txt
  pyopensn/py_env.cc
  pyopensn/py_module.cc
  pyproject.toml
  python/CMakeLists.txt
  python/lib/aquad.cc
  python/lib/console.cc
  python/lib/console.h
  python/lib/fieldfunc.cc
  python/lib/logvol.cc
  python/lib/material.cc
  python/lib/mesh.cc
  python/lib/parameter.cc
  python/lib/py_api.h
  python/lib/py_app.cc
  python/lib/py_app.h
  python/lib/py_wrappers.h
  python/lib/solver.cc
  python/lib/source.cc
  python/lib/xs.cc
  python/main.cc
  setup.py
  test/CMakeLists.txt
Labels: enhancement

#516 Bring back `find_package(Boost)`
  CMakeLists.txt
Labels: bug-fix

#521 Removing unused code from `math/framework`
  framework/math/golub_fischer/golub_fischer.cc
  framework/math/golub_fischer/golub_fischer.h
  framework/math/math.h
  framework/math/serial_newton_iteration/serial_newton_iteration.cc
  framework/math/serial_newton_iteration/serial_newton_iteration.h
  framework/math/statistics/cdfsampler.cc
  framework/math/statistics/cdfsampler.h
Labels: maintenance

#522 Adding regression test using PETSc BiCGSTAB
  test/modules/linear_boltzmann_solvers/transport_steady/tests.json
  test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2_bicgstab.lua
Labels: maintenance

#523 Correcting spelling of parameter in InputParameters API
  framework/parameters/input_parameters.cc
  framework/parameters/input_parameters.h
  test/framework/parameters/params_test_01.cc
Labels: maintenance

#526 Clean up lbs_solver IO and associated test
  modules/linear_boltzmann_solvers/lbs_solver/io/groupset_angular_flux_io.cc
  modules/linear_boltzmann_solvers/lbs_solver/io/lbs_solver_io.h
  test/modules/linear_boltzmann_solvers/transport_steady/angular_io_1d.lua
Labels: maintenance

#537 Minor fixes for Python response bindings. Fixing compiler warnings about FieldFunction destructor.
  framework/field_functions/interpolation/ffinterpolation.h
  python/lib/response.cc
Labels: bug

#543 Fixing coverage workflow.
  .github/workflows/builds.yaml
Labels: maintenance

#544 Fixing documentation generation for tutorials.
  doc/CMakeLists.txt
Labels: bug-fix

#545 Workflow updates
  .github/workflows/builds.yaml
  .github/workflows/gh-pages.yml
  .github/workflows/regression.yaml
  .github/workflows/weekly.yaml
Labels: maintenance

#548 Updating Python LBS tutorial to reflect field function interface
  tutorials/python/lbs/first/first_example.py
Labels: maintenance

#552 Fixing `make test` to correctly execute either Lua or Python tests.
  CMakeLists.txt
Labels: bug-fix

#558 Minor refactoring of log functionality. Updating Python console app.
  framework/logging/log.cc
  framework/logging/log.h
  framework/logging/log_stream.cc
  framework/logging/log_stream.h
  framework/logging/stringstream_color.cc
  framework/logging/stringstream_color.h
  python/lib/console.cc
  python/lib/console.h
  python/lib/py_app.cc
  python/lib/py_app.h
  test/lua/framework/parameters/tests.json
Labels: maintenance, bug-fix

#560 Removing noexcept from constructor for Log to fix compilation issue with GCC 9.x
  framework/logging/log.h
Labels: maintenance
