Repository Open-Sn/opensn, pull requests merged in 2025-07, with the labels that each got.

#677 Removing diffusion module
  doc/devguide/py_bindings.rst
  doc/pyapi/index.rst
  modules/diffusion/boundary.h
  modules/diffusion/cfem_diffusion_solver.cc
  modules/diffusion/cfem_diffusion_solver.h
  modules/diffusion/dfem_diffusion_solver.cc
  modules/diffusion/dfem_diffusion_solver.h
  modules/diffusion/diffusion_solver.cc
  modules/diffusion/diffusion_solver.h
  modules/diffusion/fv_diffusion_solver.cc
  modules/diffusion/fv_diffusion_solver.h
  modules/diffusion/mg_diffusion_solver.cc
  modules/diffusion/mg_diffusion_solver.h
  pyopensn/py_module.cc
  python/lib/diffusion.cc
  python/lib/py_app.cc
  python/lib/py_wrappers.h
  test/python/modules/cfem_diffusion/c_diffusion_2d_1a_linear.py
  test/python/modules/cfem_diffusion/c_diffusion_2d_2a_dir_bcs.py
  test/python/modules/cfem_diffusion/c_diffusion_2d_2b_robin_bcs.py
  test/python/modules/cfem_diffusion/c_diffusion_2d_3a_analytical_coef.py
  test/python/modules/cfem_diffusion/c_diffusion_2d_3b_analytical_coef2.py
  test/python/modules/cfem_diffusion/tests.json
  test/python/modules/dfem_diffusion/d_diffusion_2d_1a_linear.py
  test/python/modules/dfem_diffusion/d_diffusion_2d_2a_dir_bcs.py
  test/python/modules/dfem_diffusion/d_diffusion_2d_2b_robin_bcs.py
  test/python/modules/dfem_diffusion/d_diffusion_2d_3a_analytical_coef.py
  test/python/modules/dfem_diffusion/d_diffusion_2d_3b_analytical_coef2.py
  test/python/modules/dfem_diffusion/tests.json
Labels: maintenance

#678 Refactoring WGDSA/TGDSA out of `LBSProblem`
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/discrete_ordinates_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/tgdsa.cc
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/tgdsa.h
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/wgdsa.cc
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/wgdsa.h
  modules/linear_boltzmann_solvers/lbs_problem/iterative_methods/classic_richardson.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.h
  modules/linear_boltzmann_solvers/lbs_problem/preconditioning/lbs_dsa_preconditioner.cc
  modules/linear_boltzmann_solvers/lbs_problem/preconditioning/lbsmip_tgdsa_preconditioner.cc
Labels: maintenance

#686 Using adj_ instead of ass_
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds_common_data.cc
Labels: maintenance

#684 Refactoring compute functions out of `LBSProblem`
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/nl_keigen_acc_residual_func.cc
  modules/linear_boltzmann_solvers/lbs_problem/acceleration/nl_keigen_acc_solver.cc
  modules/linear_boltzmann_solvers/lbs_problem/iterative_methods/nl_keigen_ags_residual_func.cc
  modules/linear_boltzmann_solvers/lbs_problem/iterative_methods/nl_keigen_ags_solver.cc
  modules/linear_boltzmann_solvers/lbs_problem/iterative_methods/power_iteration_keigen.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_compute.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_compute.h
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
  modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.h
  modules/linear_boltzmann_solvers/solvers/nl_keigen_solver.cc
  modules/linear_boltzmann_solvers/solvers/pi_keigen_scdsa_solver.cc
  modules/linear_boltzmann_solvers/solvers/pi_keigen_smm_solver.cc
  modules/linear_boltzmann_solvers/solvers/pi_keigen_solver.cc
  modules/linear_boltzmann_solvers/solvers/steady_state_solver.cc
  python/lib/solver.cc
Labels: maintenance

#590 Adding a CMake script to configure and install dependencies
  doc/install/easy_install.rst
  doc/install/index.rst
  doc/install/install.rst
  tools/README.md
  tools/configure_dependencies.py
  tools/dependencies/CMakeLists.txt
  tools/dependencies/env_script.cmake
Labels: enhancement

#687 Removing easy install documentation.
  doc/CMakeLists.txt
  doc/install/install.rst
Labels: bug-fix

#689 Fixing segfault in FIFO sweep scheduler
  modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/scheduler/sweep_scheduler.cc
Labels: bug-fix

#696 Updating Dockerfile
  tools/Dockerfile
Labels: maintenance

#697 Updating install instructions to reflect that versions of PETSc >= 3.17 are acceptable
  doc/source/install/install.rst
Labels: documentation
